package common

const (
	MESSAGE_SUCCESS                  = "SUCCESS"
	MESSAGE_ERROR                    = "ERROR"
	MESSAGE_PONG                     = "PONG"
	MESSAGE_EXIT                     = "Bye"
	MESSAGE_NO_PWD                   = "NO_PWD"
	MESSAGE_PWD_ERROR                = "PWD_ERROR"
	MESSAGE_PORT_ERROR               = "PORT_ERROR"
	MESSAGE_PROTOCOL_ERROR           = "PROTOCOL_ERROR"
	MESSAGE_COMMAND_PARAM_ERROR      = "COMMAND_PARAM_ERROR"
	MESSAGE_ITEM_NOT_EXIST           = "ITEM_NOT_EXIST"
	MESSAGE_ITEM_IS_EMPTY            = "MESSAGE_ITEM_IS_EMPTY"
	MESSAGE_FIELD_NOT_EXIST          = "MESSAGE_FIELD_NOT_EXIST"
	MESSAGE_TABLE_NOT_EXIST          = "TABLE_NOT_EXIST"
	MESSAGE_COMMAND_NOT_FOUND        = "COMMAND_NOT_FOUND"
	MESSAGE_COMMAND_NO_LOGIN         = "COMMAND_NO_LOGIN"
	MESSAGE_COMMAND_NOT_SUPPORT_DATA = "COMMAND_NOT_SUPPORT_DATA"
	MESSAGE_SLAVEOF_HOST_ERROR       = "SLAVEOF_HOST_ERROR"
	MESSAGE_SLAVEOF_REQ_ERROR        = "MESSAGE_SLAVEOF_REQ_ERROR"
)
